### ISSUE TITLE
Ability to hide component - slots-picker/selection-single

### ISSUE THREAD

**Issue by ssahabg** [britishgas-engineering/ember-appointment-slots-pickers#28]
**Description**

Currently when we select a slot from `easy-slot-picker` component, we can see `slots-picker/selection-single` component showing message 'Arriving <<"date">> between <<"start time">> and <<"end time">>'. We cannot customise this message now. 

<img width="765" alt="Screenshot 2020-03-19 at 13 07 14" src="https://user-images.githubusercontent.com/43007822/77071665-594e8700-69e4-11ea-8b4f-98eda8e122ec.png">

**Use case**

If we use this component for the purpose of booking video / telephonic call appointment, then the message saying 'Arriving...' is not relevant.

**Request**

If we can hide message passing attribute `hideSlotSelectionMessage` to `easy-slot-picker`, we can use custom message as per the need in the application level.

**Comment by Leooo** [comment]
@ssahabg just add a custom `slots-picker/selection-single` component in your app? :)

**Comment by ssahabg** [comment]
Thanks @Leooo for the suggestion. Closing this issue.
